name: 🐞 Found a Bug? Tell Us About It! 🔍
description: 🚀 Help make our WhatsApp bot better by reporting any issues you find
title: "🚨 [Bug Report] "
labels:
  - 🐛 bug
  - 🔬 needs review
assignees:
  - hacxk  # Replace with your GitHub username

body:
  - type: markdown
    attributes:
      value: |
        # 👋 Hey there, thanks for speaking up! 

        🙌 We appreciate you taking the time to let us know about a problem with our WhatsApp bot. 
        💡 Your feedback helps us make it work better for everyone.
        📝 Fill out the info below to help us understand and fix the issue quickly:

  - type: input
    id: version
    attributes:
      label: 🤖 Bot Version
      description: Which version of the bot are you using? (You can find this in the bot's about menu)
      placeholder: For example, 2.1.0
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: 📱 What are you using?
      description: Pick the device you're using the bot on
      options:
        - 🤖 Android phone
        - 🍎 iPhone
        - 💻 WhatsApp Web or Desktop app
        - 🔮 Something else (tell us in the details below)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 What's not working right?
      description: Tell us what's going wrong. The more details, the better!
      placeholder: "For example: When I try to use the /weather command, the bot crashes and doesn't respond."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 🔄 How can we see it happen?
      description: Walk us through the steps to make the problem show up
      placeholder: |
        1. 📱 Open the chat with the bot
        2. ⌨️ Type in the command...
        3. 📤 Press send
        4. 👀 Then this happens...

  - type: textarea
    id: expected
    attributes:
      label: 🌈 What should happen instead?
      description: Tell us what you expected the bot to do
      placeholder: "I expected the bot to show me today's weather forecast for my city."

  - type: textarea
    id: additional
    attributes:
      label: 🔍 Anything else we should know?
      description: Got screenshots? Error messages? Other details? Add them here!
      placeholder: "I've attached a screenshot of the error message I'm seeing."

  - type: checkboxes
    id: terms
    attributes:
      label: 📜 One last thing...
      options:
        - label: 🤝 I agree to follow the project's Code of Conduct (be nice to each other!)
          required: true

  - type: markdown
    attributes:
      value: |
        # 🌟 You're awesome! 

        🙏 Thanks so much for helping us improve the bot. We'll check this out and get back to you soon.

        🛠️ If you run into any trouble with Node.js or npm packages while using the bot, try these quick fixes:
        - 📋 Share any error messages you see (they're super helpful!)
        - 🔄 Try uninstalling and reinstalling the bot or its packages

        😊 Keep being great, and happy chatting! 💬
