name: 💡 Got a Cool Idea? 🌟
description: Share your awesome feature ideas for our WhatsApp bot! 🤖✨
title: "✨ [Feature Request]  Your Idea Here 💭"
labels:
  - enhancement 🚀
body:
  - type: markdown
    attributes:
      value: |
        Hey there! 👋 We're thrilled to hear your ideas for making our WhatsApp bot even better! 🎉
        If you've got a cool feature in mind, please fill out this form to tell us all about it. 🌟💡
  - type: input
    id: feature-name
    attributes:
      label: What should we call this feature? 🏷️💭
      description: Give your feature a short, descriptive name. 📝👌
    validations:
      required: true ✅
  - type: textarea
    id: description
    attributes:
      label: What's this feature all about? 🚀🔍
      description: Explain what the feature does and why it would be awesome to have. 🌈😃
      placeholder: "This feature would allow the bot to... 🤖💬"
    validations:
      required: true ✅
  - type: textarea
    id: use-case
    attributes:
      label: How would people use this feature? 🎯👥
      description: Describe a specific scenario where this feature would come in handy. 🛠️💡
      placeholder: "For example, I would use this feature to... 🙋‍♂️💭"
  - type: textarea
    id: mockups
    attributes:
      label: Got any visual ideas? (Optional) 🎨👀
      description: If you have sketches, drawings, or screenshots showing how this feature might look, feel free to share them here. 📸✏️
  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you? 🌟🔥
      description: Let us know how much you'd like to see this feature added. 📊💖
      options:
        - Nice to have 😊
        - Pretty important 🙌
        - Absolutely essential 🔥
    validations:
      required: false ❓
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct 📜🤝
      options:
        - label: I agree to follow the project's Code of Conduct 🤓✅
          required: true ✔️
  - type: markdown
    attributes:
      value: |
        Thanks a bunch for sharing your idea! 🙌🎉
        We truly appreciate your input and will definitely consider it as we continue to enhance the bot. ✨🚀