name: 🚨 Security Vulnerability Alert 🛡️
description: 🔐 Report a critical security vulnerability you've discovered in our system 🕵️‍♂️
title: "🚩 [SECURITY ALERT]: "
labels: ["🔒 security", "🔥 priority:high"]
body:
  - type: markdown
    attributes:
      value: |
        # 🚀 Thank You for Your Vigilance! 🦸‍♂️🦸‍♀️

        We greatly appreciate your commitment to responsible disclosure of potential security vulnerabilities. 
        Your efforts help us maintain a safer digital environment for all our users. 🌐🛡️

        Please provide as much detailed information as possible in the sections below. 
        Together, we can make our system more secure! 💪🔒

  - type: textarea
    id: description
    attributes:
      label: 📝 Vulnerability Description
      description: |
        🔍 Please explain the vulnerability in detail and its potential impact on our system.
        The more information you can provide, the better we can address the issue.
      placeholder: "A potential message hijacking vulnerability exists in the..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: |
        🧪 If possible, provide a step-by-step guide on how to reproduce the vulnerability.
        Clear instructions will help us quickly verify and address the issue.
      placeholder: |
        1. Log in to the system
        2. Navigate to...
        3. Attempt to...
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: 💥 Potential Impact
      description: |
        🔮 Describe the potential consequences if this vulnerability were to be exploited.
        Consider various scenarios and the scope of the impact.
      placeholder: |
        If exploited, this vulnerability could lead to:
        - Unauthorized access to user data
        - System downtime
        - ...

  - type: dropdown
    id: severity
    attributes:
      label: 🚦 Estimated Severity
      description: Based on your assessment, how severe do you consider this vulnerability?
      options:
        - 🟢 Low - Minor impact
        - 🟡 Medium - Moderate impact
        - 🟠 High - Significant impact
        - 🔴 Critical - Severe, immediate threat
    validations:
      required: true

  - type: input
    id: affected-versions
    attributes:
      label: 🎯 Affected Versions/Components
      description: 📊 If known, specify which versions or components of our system are affected.
      placeholder: "v2.1.0, Login module, etc."

  - type: textarea
    id: additional-info
    attributes:
      label: 📎 Additional Information
      description: |
        🧩 Any other details, context, or files that might be helpful in understanding and addressing the vulnerability.
      placeholder: "Attach screenshots, logs, or any other relevant information here."

  - type: checkboxes
    id: terms
    attributes:
      label: 🤝 Responsible Disclosure Agreement
      options:
        - label: I agree to maintain confidentiality about this vulnerability until it has been addressed by the security team.
          required: true

  - type: markdown
    attributes:
      value: |
        ## 🎖️ Thank You for Your Contribution to Our Security! 🛡️

        Your diligence in reporting this potential vulnerability is invaluable. 
        Our security team will review your report as soon as possible and may contact you for further information.

        Stay vigilant, stay secure! 🦉🔐
